config/routes.rb
Rails.application.routes.draw do
  get 'statistics/index'

  get 'repairs/new'

  get 'repairs/show'

  get 'sessions/new'

  

  resources :operators
  resources :points
  resources :statistics
  

  resources :users
  resources :repairs

  resources :sessions

  root 'operators#index'
  get '/punkty' => 'points#index'
  
  
  get "log_out", to: "sessions#destroy", :as => "log_out"
  get "log_in", to:  "sessions#new", :as => "log_in"
  get "sign_up", to:  "users#new", :as => "sign_up"
  get "session/:id", to:  "sessions#change"
  
  
  
 
  get "/points/:point_id/repairs/new", to: "repairs#new"
  get "/points/:point_id/repairs/:id", to: "repairs#show"
  get "/points/:point_id/repairs/:id", to: "repairs#destroy"
  
  
  
  resources :points do
    resources :repairs
  end
  
  resources :operators do
    resources :points
  end
  
  

  

  
  

end

app/models/point.rb
class Point < ActiveRecord::Base  
  belongs_to :operator
  has_many :repairs, :dependent => :destroy
  
  validates_presence_of :address, :town
  validates_uniqueness_of :address
 
  #do_not_validate_attachment_file_type :photo
  #do_not_validate_attachment_file_type :photo
  
 
  #paperclip gem dodajacy/wyswietlajacy zdjecia
  
  #Metoda wyszukująca napisana z palca
  def self.search(search, column)
    if search 
      #points=Point.arel_table
     
      case column
      when "1"
        Point.where("last_name LIKE ?", "%#{search}%")
      when "2"
        Point.where("address LIKE ?", "%#{search}%")
      when "3"
        Point.where("town LIKE ?", "%#{search}%")
      else
        Point.all 
      end
      #errors.add(:search, "Please type in the correct email address.")
  
      
      #CALOSC PO WSZYSTKICH KOLUMNACH
      #Point.joins(:operator).where('last_name LIKE ? OR address LIKE ? OR town LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%") 
   
    else 
      Point.all
    end
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]
  #before_action :validate, only: :name -- nie wiem co to jest
  
  
  #Przed wywolaniem wykonaj instrukcje autentykacji w application controller
  before_filter :authenticate, except: [:index, :show]
  
  helper_method :sort_column, :sort_direction
  
  # GET /points
  # GET /points.json
  # Do index dołączona paginacja i metoda wyszukująca
  def index
    if params[:operator_id]
      @points = Operator.find(params[:operator_id]).points.paginate(:per_page => 20, :page => params[:page]).search(params[:search],params[:column])
    else
      @points = Point.joins(:operator).paginate(:per_page => 20, :page => params[:page]).search(params[:search],params[:column]).order(sort_column + " " + sort_direction)
    end
  end
   
  def sort_column
    Point.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  
  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)
    
    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_point
    @point = Point.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def point_params
    params.require(:point).permit(:address, :town, :email, :telephone, :started_at, :operator_id, :owner,:ip_address, :point_id, :ip_pos, :ip_printer)
  end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<%= form_for (@point), :html => {:multipart => true} do |f| %>
  <% if @point.errors.any? %>
    <div class="alert alert-danger">
      <strong><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</strong>

      <ul>
        <% @point.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-4">
    <div class="form-group">
      <label><%= f.label :point_id %></label>
      <%= select_tag('point[operator_id]',options_from_collection_for_select(Operator.all, "id", "last_name", @point.operator_id), :class => 'form-control') %>


      <label><%= f.label :address %></label>
      <%= f.text_field :address, :class => 'form-control' %>


      <label><%= f.label :town, "City" %></label>
      <%= f.text_field :town, :class => 'form-control' %>


      <label><%= f.label :owner, "Owner" %></label>
      <%= f.text_field :owner, :class => 'form-control' %>

      <label><%= f.label :email %></label>
      <%= f.text_field :email, :class => 'form-control' %>

      <label><%= f.label :telephone %></label>
      <%= f.text_field :telephone, :class => 'form-control' %>

      <label><%= f.label :ip_address %></label>
      <%= f.text_field :ip_address, :class => 'form-control' %>

      <label><%= f.label :ip_printer, "IP Printer" %></label>
      <%= f.text_field :ip_printer, :class => 'form-control' %>

      <label><%= f.label :ip_pos, "IP POS" %></label>
<%= f.text_field :ip_pos, :class => 'form-control' %>
      <br>
      <label><%= f.label :started_at %></label>
      <%= f.text_field :started_at, :id =>'datepicker', :class => 'form-control' %> 




      <br>
      <%= f.submit 'Save point',  :class => 'btn btn-default' %>
<%= link_to 'Back', points_path,  :class => 'btn btn-default' %>

    </div>
  </div>
<% end %>

app/views/points/_new_form.html.erb
<% @point = Point.new %>
<%= form_for (@point), :html => {:multipart => true} do |f| %>
  <% if @point.errors.any? %>
    <div class="alert alert-danger">
      <strong><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</strong>

      <ul>
        <% @point.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-4">
    <div class="form-group">

      <label><%= f.label :point_id %></label>
      <%= select_tag('point[operator_id]',options_from_collection_for_select(Operator.all, "id", "last_name", @point.operator_id),:class => 'form-control' ) %>

      <label><%= f.label :address %></label>
      <%= f.text_field :address, :class => 'form-control' %>

      <label><%= f.label :town, "City" %></label>
      <%= f.text_field :town, :class => 'form-control' %>

      <label><%= f.label :owner, "Owner" %></label>
      <%= f.text_field :owner, :class => 'form-control' %>

      <label><%= f.label :email %></label>
      <%= f.text_field :email, :class => 'form-control' %>

      <label><%= f.label :telephone %></label>
      <%= f.text_field :telephone, :class => 'form-control' %>

      <label><%= f.label :ip_address, "IP Address" %></label>
      <%= f.text_field :ip_address, :class => 'form-control' %>

      <label><%= f.label :ip_printer, "IP Printer" %></label>
      <%= f.text_field :ip_printer, :class => 'form-control' %>

      <label><%= f.label :ip_pos, "IP POS" %></label>
      <%= f.text_field :ip_pos, :class => 'form-control' %>

      <label><%= f.label :started_at %></label>
      <%= f.text_field :started_at, :id =>'datepicker', :class => 'form-control' %> 


      <div class="actions">
        <br>
        <%= f.submit 'New point',  :class => 'btn btn-default' %>
      </div>

    </div>
  </div>
<% end %>

app/views/points/_search.html.erb
<%= form_tag points_path,  :method => :get do %>
<p>Search: <%= text_field_tag :search, params[:search], :placeholder => "Search words...", :class=>"form-control", :id => 'search' %> </p>
  <%# Ukryte pola uzywane do zachowania parametrow wyszukiwania%>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <%#*Do wyboru opcje params[:column] ustawia wybor listy na ten z GET%>
<p>by  <%=  select_tag(:column, options_for_select([["Operator",1],["Address",2],["City",3]], params[:column]), :class=>"form-control") %> </p>
  <%#= select_tag :table, options_for_select(Operator.column_names)  %>
  <button class="btn btn-default"> <%= link_to "Reset", points_path%></button>
  <%= submit_tag "Search", :name => nil, :class => 'btn btn-default' %>
<% end %> 

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

app/views/points/index.html.erb
# encoding: utf-8
<% if notice %>
<div class='alert alert-success'>
  <strong>Done!</strong>
  <p id="notice"><%= notice %></p>
</div>
<% end %>
<h1>Listing points <%= @points.count %> </h1>

<%#*Forumlarz wyszukujący tresc%>

<br>
<%= render :partial => "search" %>
<br><br>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>

      <th><%= sortable "first_name","Operator" %></th>
      <th><%= sortable "address", "Address"%></th>
      <th><%= sortable "town", "City" %></th>
      <th>Photo</th>

<%#*<th>Owner</th>%>
<%#*<th>Email</th>%>
<%#*<th>Telephone</th>%>
<%#*<th>IP</th>%>
<%#*<th>Updated</th>%>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>

        <td><%= point.operator.nil? ? "No operator" : point.operator.last_name %></td>
        <td><%= point.address %></td>
        <td><%= point.town %></td>
        <td><%= Dir["public/images/uploads/#{point.id}/*"].empty? ? "" : "V"%> </td>

  <%#*<td><%= point.owner.blank? ? "-" : point.owner.force_encoding('utf-8') </td>%>
  <%#*<td><%= point.email.blank? ? "-" : (mail_to point.email) </td>%>
  <%#*<td><%= point.telephone.blank? ? "-" : point.telephone </td>%>
  <%#*<td><%= point.ip_address.blank? ? "-" : point.ip_address </td>%> 
  <%#*<td><%= point.updated_at </td>%>

        <td style="text-align: center;"><%= link_to 'View Point Repairs', point_repairs_path(:point_id => point.id), :class => "btn btn-xs btn-primary" %></td>
        <td style="text-align: center;"><%= link_to 'Show', point, :class => "btn btn-xs btn-primary" %></td>
        <td style="text-align: center;"><%= link_to 'Edit', edit_point_path(point), :class => "btn btn-xs btn-primary" %></td>
        <td style="text-align: center;"><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="digg-pagination">
<%= will_paginate @points %>
</div>
<br>

<%= link_to 'Back', points_path,  :class => 'btn btn-default' %>
<br><br>
<%  if !current_user.nil? %>
   <h1 class="page-header">Add new point:</h1>
  <%= render :partial => "new_form" %>
<%  end %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

app/views/points/show.html.erb
<% if notice %>
<div class='alert alert-success'>
  <strong>Done!</strong>
  <p id="notice"><%= notice %></p>
</div>
<% end %>
<p>
  <strong>Operator:</strong>
  <%= @point.operator.last_name+' '+@point.operator.first_name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @point.address %>
</p>

<p>
  <strong>Town:</strong>
  <%= @point.town %>
</p>
<p>
  <strong>Owner:</strong>
  <%= @point.owner.blank? ? "-" : @point.owner %>
</p>

<p>
  <strong>Email:</strong>
  <%= @point.email.blank? ? "-" : @point.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @point.telephone.blank? ? "-" : @point.telephone %>

</p>
<p>
  <strong>IP Adress:</strong>
  <%= @point.ip_address.blank? ? "-" : @point.ip_address %>

</p>
<p>
  <strong>IP POS:</strong>
  <%= @point.ip_pos.blank? ? "-" : @point.ip_pos %>

</p>
<p>
  <strong>IP Printer:</strong>
  <%= @point.ip_printer.blank? ? "-" : @point.ip_printer %>

</p>

<p>
  <strong>Started at:</strong>
  <%= @point.started_at %>
</p>

  <strong>Example:</strong>
  <p>
  <% @files = Dir.glob("public/images/uploads/#{@point.id}/*") 
     @files.each do |f| %>
     <%= link_to (image_tag "uploads/#{@point.id}/#{ File.basename(f)}", :width => 200),  "/images/uploads/#{@point.id}/#{ File.basename(f)}", target: "_blank" %> 
  <% end %>

</p>








<%= link_to 'New', new_point_path, :class => 'btn btn-default' %> 
<%= link_to 'Edit', edit_point_path(@point), :class => 'btn btn-default' %> 
<%= link_to 'Back', :back, :class => 'btn btn-default' %>