config/routes.rb
Rails.application.routes.draw do
  get 'statistics/index'

  get 'repairs/new'

  get 'repairs/show'

  get 'sessions/new'

  

  resources :operators
  resources :points
  resources :statistics
  

  resources :users
  resources :repairs

  resources :sessions

  root 'operators#index'
  get '/punkty' => 'points#index'
  
  
  get "log_out", to: "sessions#destroy", :as => "log_out"
  get "log_in", to:  "sessions#new", :as => "log_in"
  get "sign_up", to:  "users#new", :as => "sign_up"
  get "session/:id", to:  "sessions#change"
  
  
  
 
  get "/points/:point_id/repairs/new", to: "repairs#new"
  get "/points/:point_id/repairs/:id", to: "repairs#show"
  get "/points/:point_id/repairs/:id", to: "repairs#destroy"
  
  
  
  resources :points do
    resources :repairs
  end
  
  resources :operators do
    resources :points
  end
  
  

  

  
  

end

app/models/operator.rb
class Operator < ActiveRecord::Base
  has_many :points, :dependent => :destroy
  
  validates_presence_of  :last_name, :first_name
  #validates_numericality_of :telephone
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  before_action :set_operator, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, except: [:index, :show]
  
  helper_method :sort_column, :sort_direction


  # GET /operators
  # GET /operators.json
   def index
    
     
      @operators = Operator.paginate(:per_page => 20, :page => params[:page]).order(sort_column + " " + sort_direction)
   
  end


  # GET /operators/1
  # GET /operators/1.json
  def show
  end
  
  def sort_column
    Operator.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end



  # GET /operators/new
  def new
    @operator = Operator.new
  end

  # GET /operators/1/edit
  def edit
  end

  # POST /operators
  # POST /operators.json
  def create
    @operator = Operator.new(operator_params)

    respond_to do |format|
      if @operator.save
        format.html { redirect_to @operator, notice: 'Operator was successfully created.' }
        format.json { render :show, status: :created, location: @operator }
      else
        format.html { render :new }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operators/1
  # PATCH/PUT /operators/1.json
  def update
    respond_to do |format|
      if @operator.update(operator_params)
        format.html { redirect_to @operator, notice: 'Operator was successfully updated.' }
        format.json { render :show, status: :ok, location: @operator }
      else
        format.html { render :edit }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operators/1
  # DELETE /operators/1.json
  def destroy
    @operator.destroy
    respond_to do |format|
      format.html { redirect_to operators_url, notice: 'Operator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_operator
    @operator = Operator.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def operator_params
    params.require(:operator).permit(:first_name, :last_name, :email, :telephone)
  end
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/views/operators/_form.html.erb
<%= form_for(@operator) do |f| %>
  <% if @operator.errors.any? %>
    <div class="alert alert-danger">
      <strong><%= pluralize(@operator.errors.count, "error") %> prohibited this operator from being saved:</strong>

      <ul>
        <% @operator.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-lg-4">
    <div class="form-group">

      <%= f.label :first_name %>
      <%= f.text_field :first_name, :class => 'form-control' %>


      <%= f.label :last_name %>
      <%= f.text_field :last_name, :class => 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, :class => 'form-control' %>

      <%= f.label :telephone %>
      <%= f.text_field :telephone, :class => 'form-control' %>
      <br>

      <div class="actions">
        <%= link_to 'Back', points_path,  :class => 'btn btn-default' %>
        <%= f.submit 'New operator',  :class => 'btn btn-default' %>
      </div>


    </div>
  </div>
<% end %>

app/views/operators/edit.html.erb
<h1>Editing operator</h1>

<%= render 'form' %>

<%= link_to 'Show', @operator %> |
<%= link_to 'Back', operators_path %>

app/views/operators/index.html.erb
<% if notice %>
<div class='alert alert-success'>
  <strong>Done!</strong>
  <p id="notice"><%= notice %></p>
</div>
<% end %>
<h1>Listing operators <%= @operators.count-1 %></h1>
<div class="table-responsive">

  <table class="table table-bordered table-hover table-striped">
    <thead>
      <tr>
        <th>Lp.:</th>

        <th><%= sortable "first_name","First Name" %></th>
        <th><%= sortable "last_name","Last Name" %></th>
        <th><%= sortable "last_name","Number of points" %></th>
        <th><%= sortable "email","Email" %></th>
        <th><%= sortable "telephone","Telephone" %></th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>

      <% @operators.each_with_index do |operator,i| %>
        <% next if operator.last_name == "Brak" %>
        <tr>
          <td><%= i %>.</td>
          <td><%= operator.first_name %></td>
          <td><%= operator.last_name %></td>
          <td><%= operator.points.count %></td>

          <td><%= operator.email.blank? ? "-" : (mail_to operator.email) %></td>
          <td><%= operator.telephone.blank? ? "-" : operator.telephone %></td>
          <td style="text-align: center;"><%= link_to 'View operators points', operator_points_path(:operator_id => operator.id), :class => "btn btn-xs btn-primary" %></td>
          <td style="text-align: center;"><%= link_to 'Show', operator, :class => "btn btn-xs btn-primary" %></td>
          <td style="text-align: center;"><%= link_to 'Edit', edit_operator_path(operator), :class => "btn btn-xs btn-primary" %></td>

          <td style="text-align: center;"><%= link_to 'Destroy', operator, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-xs btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @operators %>
<br>

<%= link_to 'New Operator', new_operator_path, :class => "btn btn-lg btn-default" %>

app/views/operators/new.html.erb
<h1>New operator</h1>

<%= render 'form' %>

app/views/operators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @operator.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @operator.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @operator.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @operator.telephone %>
</p>

<%= link_to 'Edit', edit_operator_path(@operator), :class => 'btn btn-default' %> 
<%= link_to 'Back', operators_path, :class => 'btn btn-default' %>