config/routes.rb
Rails.application.routes.draw do
  get 'statistics/index'

  get 'repairs/new'

  get 'repairs/show'

  get 'sessions/new'

  

  resources :operators
  resources :points
  resources :statistics
  

  resources :users
  resources :repairs

  resources :sessions

  root 'operators#index'
  get '/punkty' => 'points#index'
  
  
  get "log_out", to: "sessions#destroy", :as => "log_out"
  get "log_in", to:  "sessions#new", :as => "log_in"
  get "sign_up", to:  "users#new", :as => "sign_up"
  get "session/:id", to:  "sessions#change"
  
  
  
 
  get "/points/:point_id/repairs/new", to: "repairs#new"
  get "/points/:point_id/repairs/:id", to: "repairs#show"
  get "/points/:point_id/repairs/:id", to: "repairs#destroy"
  
  
  
  resources :points do
    resources :repairs
  end
  
  resources :operators do
    resources :points
  end
  
  

  

  
  

end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :user
  belongs_to :point
  
  validates_presence_of :description
  validates :status, :inclusion => { :in => [true, false] }
  
  
  #Metoda wyszukująca napisana z palca
  def self.search(search)
    if search 
      #CALOSC PO WSZYSTKICH KOLUMNACH
      Repair.joins(:user).where('email LIKE ? OR description LIKE ? OR date LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%") 
   
    else 
      Repair.all
    end
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: [:show, :edit, :update, :destroy]
  
  #before action dla zagniezdzonych formularzy wyszukuje point
  before_action :set_point
  before_filter :authenticate, except: [:index, :show]
  
  
  helper_method :sort_column, :sort_direction


  # GET /repairs
  # GET /repairs.json
  def index
    
    @repairs = Point.find(params[:point_id]).repairs.paginate(:per_page => 20, :page => params[:page]).order('date DESC').search(params[:search])
    #@repairs = Repair.all 
  end
  

  # GET /repairs/1
  # GET /repairs/1.json
  def show
    
  end
  


  
  def sort_column
    Repair.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end



  # GET /repairs/new
  def new
    #@point = Point.find(params[:point_id])
    @repair = @point.repairs.build  
  end

  # GET /repairs/1/edit
  def edit
    
    
  end

  # POST /repairs
  # POST /repairs.json
  def create
    @repair = @point.repairs.build(repair_params)
    #@repair = 66
    
    respond_to do |format|
      if @repair.save
        #metoda show
        #format.html { redirect_to [@point,@repair], notice: 'Repair was successfully created.' }
        
        #metoda index repairs
        format.html { redirect_to point_repairs_path(@point), notice: 'Repair was successfully created.' }
        format.json { render :show, status: :created, location: @repair }
      else
        format.html { render :new}
        format.json { render json: @repair.errors, status: :unprocessable_entity }       
      end    
    end
  end

  # PATCH/PUT /repairs/1
  # PATCH/PUT /repairs/1.json
  def update
 
    respond_to do |format|
      if @repair.update(repair_params)
        format.html { redirect_to [@point,@repair], notice: 'Repair was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair }
      else
        format.html { render :edit }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    
    @repair.destroy
    respond_to do |format|
      format.html { redirect_to point_repairs_url(@point), notice: 'Repair was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_repair
    @repair = Repair.find(params[:id])
  end
  
   def set_point
      @point = Point.find(params[:point_id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
  def repair_params
    params.require(:repair).permit(:description, :point_id, :user_id, :status, :date)
  end
  
  
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/repairs/_form.html.erb
<%= form_for [@point,@repair], :html => {:multipart => true} do |f| %>
  <% if @repair.errors.any? %>
    <div class="alert alert-danger">
      <strong><%= pluralize(@repair.errors.count, "error") %> prohibited this repair from being saved:</strong>

      <ul>
        <% @repair.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-4">
    <div class="form-group">

      <label> <%= f.label :description %></label>
    <%= f.text_area :description, :cols => 40, :rows => 10, :class => 'form-control'  %>

    <label><%= f.label :status %></label>
    <%= f.text_field :status, :class => "form-control" %>

  
    <label><%= f.label :date %></label>
    <%= f.text_field :date, :id =>'datepicker', :class => 'form-control' %> 
 
    <%= f.hidden_field :point_id, :value => params[:point_id] %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  
<br>
    <%= f.submit 'Save repair',  :class => 'btn btn-default' %>
    <%= link_to 'Back', :back,  :class => 'btn btn-default' %>
  </div>
</div>

<% end %>

app/views/repairs/_search.html.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>


<%= form_tag point_repairs_path, :controller => 'repair', :action => 'search', :method => :get do %>
<p>Search: <%= text_field_tag :search, params[:search], :placeholder => "Search words...", :class=>"form-control", :id => 'search' %> </p>
  <%# Ukryte pola uzywane do zachowania parametrow wyszukiwania%>
  <button class="btn btn-default"> <%= link_to "Reset", point_repairs_path %></button>
  <%= submit_tag "Search", :name => nil, :class => 'btn btn-default' %>
<% end %> 

app/views/repairs/edit.html.erb
<h1>Editing repair</h1>

<%= render 'form' %>

app/views/repairs/index.html.erb
<% if notice %>
  <div class='alert alert-success'>
    <strong>Done!</strong>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>
<div class="page-header">
  <% @point = Point.find(params[:point_id]) %>
  <h1>Listing repairs of <%= @point.town+', '+@point.address %> </h1>
</div>

  <%= render :partial => "search" %>

<br><br>



<% if @repairs.size == 0 %>
  <% flash[:alert] =  "No repairs found" %>


  <% flash.each do |name, msg| %>
    <div class="alert alert-danger"> 
      <strong> Prohibited errors:</strong>
      <ul>  
        <li><%= content_tag :div, msg, :id => "flash_#{name}" %></li>

      </ul>
    </div>  
  <% end %>


<% else %>
  <div style="width:20px; height: 20px; background-color:  #FAF2CC; float:left;"></div> - older than one week<br><br>
  <div style="width:20px; height: 20px; background-color:  #F2DEDE; float:left;"></div> - older than two weeks<br><br>
  <div class="table-responsive">
    <table class="table table-bordered table-hover table-striped">
      <thead>
        <tr>

          <th>Description</th>
          <th>Repairer</th>
          <th>Status</th>
          <th>Date</th>

  <%#*<th>Owner</th>%>
  <%#*<th>Email</th>%>
  <%#*<th>Telephone</th>%>
  <%#*<th>IP</th>%>
  <%#*<th>Updated</th>%>
          <th colspan="3"></th>
        </tr>
      </thead>


      <tbody>

      <% end %>
      <% #@repairs = Repair.point %>

      <% @repairs.each do |repair| %>
        <% @date = 1.weeks.ago %>
        <% @date2 = 2.weeks.ago %>

        <% if (repair.date < @date) && (repair.status == false) && (repair.date > @date2) %>
          <tr class="warning">

          <% else %>
          <tr class="success">
          <% end %>
          <% if (repair.date < @date2) && (repair.status == false)%>
          <tr class="danger">


          <% end %>

          <td style="width:400px;"><%= repair.description.html_safe %></td>
          <td><%= repair.user.email %></td>
          <td><%=  repair.status ? 'Done' : 'Need atention' %></td>
          <td><%= repair.date %></td>


  <%#*<td><%= point.owner.blank? ? "-" : point.owner.force_encoding('utf-8') </td>%>
  <%#*<td><%= point.email.blank? ? "-" : (mail_to point.email) </td>%>
  <%#*<td><%= point.telephone.blank? ? "-" : point.telephone </td>%>
  <%#*<td><%= point.ip_address.blank? ? "-" : point.ip_address </td>%> 
  <%#*<td><%= point.updated_at </td>%>



          <td style="text-align: center;"><%= link_to 'Show', point_repair_path(:id => repair), :class => "btn btn-xs btn-primary"  %></td>
          <td style="text-align: center;"><%= link_to 'Edit', edit_point_repair_path(:id =>repair), :class => "btn btn-xs btn-primary"  %></td>
          <td style="text-align: center;"><%= link_to 'Destroy', point_repair_path(:id => repair, :point_id => params[:point_id]), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-xs btn-danger" %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>
<div class="digg-pagination">
  <%= will_paginate @repairs %>
</div>
<br>

<%= link_to 'New Repair', new_point_repair_path(@point),  :class => 'btn btn-default' %>  <%= link_to 'Back', :back,  :class => 'btn btn-default' %>

app/views/repairs/new.html.erb
<h1>New Repair</h1>

<%= render 'form' %>

app/views/repairs/show.html.erb
<% if notice %>
<div class='alert alert-success'>
  <strong>Done!</strong>
  <p id="notice"><%= notice %></p>
</div>
<% end %>

<p>
  <strong>Repairer:</strong>
  <%= @repair.user.first_name+' '+@repair.user.last_name %>
</p>
<p>
  <strong>Description:</strong>
<div style="width:400px;"><%= @repair.description.html_safe %>
</p>

<p>
  <strong>Status:</strong>
  <%= @repair.status %>
</p>
<p>
  <strong>Date:</strong>
  <%= @repair.date  %>
</p>




<%
 @point = Point.find(params[:point_id])
%>


<%= link_to 'New', new_point_repair_path(@point), :class => 'btn btn-default' %> 
<%= link_to 'Edit', edit_point_repair_path(@point,@repair), :class => 'btn btn-default' %> 
<%= link_to 'Back', point_repairs_path(@point), :class => 'btn btn-default' %>