config/routes.rb
Rails.application.routes.draw do
  get 'statistics/index'

  get 'repairs/new'

  get 'repairs/show'

  get 'sessions/new'

  

  resources :operators
  resources :points
  resources :statistics
  

  resources :users
  resources :repairs

  resources :sessions

  root 'operators#index'
  get '/punkty' => 'points#index'
  
  
  get "log_out", to: "sessions#destroy", :as => "log_out"
  get "log_in", to:  "sessions#new", :as => "log_in"
  get "sign_up", to:  "users#new", :as => "sign_up"
  get "session/:id", to:  "sessions#change"
  
  
  
 
  get "/points/:point_id/repairs/new", to: "repairs#new"
  get "/points/:point_id/repairs/:id", to: "repairs#show"
  get "/points/:point_id/repairs/:id", to: "repairs#destroy"
  
  
  
  resources :points do
    resources :repairs
  end
  
  resources :operators do
    resources :points
  end
  
  

  

  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Punkty</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>



    <div id="wrapper">

      <!-- Navigation -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">SB Admin</a>
        </div>
        <!-- Top Menu Items -->
        <ul class="nav navbar-right top-nav">

          <%  if current_user.nil? %>
            <li class="dropdown">
              <%= link_to "Log in", log_in_path, :class => "dropdown-toggle" %>

            </li>
          </ul>


        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%=  current_user.email %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
               
                 <%= link_to raw("<i class='fa fa-fw fa-user'> </i> Profile"), user_path(:id => current_user.id)  %>
              </li>
              <li>
                <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
              </li>
              <li>
                <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
              </li>
              <li class="divider"></li>
              <li>

             

               <%= link_to raw("<i class='fa fa-fw fa-power-off'> </i> Log out (#{current_user.email})"), log_out_path  %>
                

              </li>
            </ul>
          </li>
        <% end %>
        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div  class="collapse navbar-collapse navbar-ex1-collapse">
          <ul style="height: 1000px;" class="nav navbar-nav side-nav">

            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-user"></i> Operators <i class="fa fa-fw fa-caret-down"></i></a>
              <ul id="demo" class="collapse">
                <li>
                  <%= link_to 'List Operators', operators_path %>
                </li>
                <li>
                  <%= link_to 'New Operator', new_operator_path %>

                </li>
              </ul>
            </li>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#demo1"><i class="fa fa-fw fa-desktop"></i> Points <i class="fa fa-fw fa-caret-down"></i></a>
              <ul id="demo1" class="collapse">
                <li>
                  <%= link_to 'List Points', points_path %>
                </li>
                <li>

                  <%= link_to 'New Point', new_point_path%>
                </li>
              </ul>
            </li>
            <li>
               <%= link_to raw("<i class='fa fa-fw fa-bar-chart-o'> </i> Statistics"), statistics_path  %>
             
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </nav>

      <div id="page-wrapper">

        <div class="container-fluid">

          <%= yield %>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->









  </body>
</html>